### ISSUE TITLE
Change color for kanban

### ISSUE THREAD

**Issue by MyEnthusiastic** [hannesfrank/remnote-library#16]
How can I change the color like this?
![image](https://user-images.githubusercontent.com/54618402/128592606-1d4fcb9f-6ee6-4976-8d93-f96c4fe3309c.png)

really amazing, thank you

**Comment by hannesfrank** [comment]
You have multiple options:

1. Overwrite the kanban color by inserting this code _*after*_ the kanban board code:

```css
.tree-node-container[data-rem-container-tags~=kanban] > .TreeNode > .tree-node-container[data-rem-container-tags~="tree-blue"] {
    background-color: rgb(150, 150, 255);
}
```

2. Increase the priority of the background color tag by adding an `!important`:

```css
[data-rem-container-tags~="tree-blue"] { background-color: rgb(100,200,255) !important; }
```
